Update biopypir_ci_workflow.yml

diff --git a/.github/workflows/biopypir_ci_workflow.yml b/.github/workflows/biopypir_ci_workflow.yml
--- a/.github/workflows/biopypir_ci_workflow.yml
+++ b/.github/workflows/biopypir_ci_workflow.yml
@@ -1,28 +1,39 @@
 ---
 name: BIOPYPIR-APPROVED
 on: 
+  schedule:
+    - cron: '0 0 * * 0'  #'0 12 * * 7'   #  - cron: '0 12 * * 7'   # 12:00 UTC every Sat  
   push:
-  pull_request:
-  #schedule:
-  #  - cron: '0 12 * * 7'   # 12:00 UTC every Sat
-    
 jobs:
   biopypir_testing:
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
       matrix:
-        python-version: [3.5,3.6,3.7] 
+        python-version: [3.6,3.7] 
         os: [ubuntu-latest, macOS-latest] 
-        #architecture: [x64]
     env: 
       WORKSPACE: ${{ github.workspace }} # /home/runner/work/scedar/scedar
       REPO: ${{ github.repository }}
     steps:
+    - name: Create cache file
+      run: mkdir check-SHA; echo ${{ github.sha }} > github-sha.txt; cat github-sha.txt
+    #===============================================#
+    #- name: Check SHA
+    # id: check_sha
+    #  uses: actions/cache@v1
+    #  with:
+    #    path: check-SHA
+    #    key: check-SHA-${{ github.sha }}
+    #===============================================#
+    #- name: Some subsequent steps
+    #  if: steps.check_sha.outputs.cache-hit != 'true'
+    #  run: echo "Cache hit found...Execute the subsequent steps" #; exit 1 # no way to exit nicely?
+    #===============================================#
     - name: STEP 1. Check-Out Repo 
       uses: actions/checkout@v2     
     #===============================================#
-    - name: ${{matrix.os}}-py${{matrix.python-version}}
+    - name: Set Up ${{matrix.os}}-py${{matrix.python-version}}
       uses: actions/setup-python@v1
       with:
         python-version: ${{ matrix.python-version }}       
@@ -30,98 +41,100 @@ jobs:
     - name: STEP 3. Install dependencies
       run: |
         pip install pylint
-      #  pip install --upgrade pip setuptools wheel
-      #  pip install --no-binary :all: nmslib
-      #  pip install .
-      #  pip install pytest
-      #  pip install pytest-cov
-      #  pip install python-coveralls
+        pip install --upgrade pip setuptools wheel
+        pip install --no-binary :all: nmslib
+        pip install .
+        pip install pytest
+        pip install pytest-cov
+        pip install python-coveralls
       #pip install coveralls
-      #pip install junit2html
-      #pip list -v  
     #===============================================#
     - name: simple linter
       id: linter
       run: |
           chmod +x .github/workflows/biopypir_helper.sh
-          .github/workflows/biopypir_helper.sh  "LINT"
+          .github/workflows/biopypir_helper.sh  "LINT"  "${{github.repository}}"
     #===============================================#
-    #- name: test build status
-    #  id: builder
-    #  run: .github/workflows/biopypir_helper.sh  "BUILD"
+    - name: test build status
+      id: builder
+      run: .github/workflows/biopypir_helper.sh  "BUILD"
     #===============================================#
-   # - name: simple pytest
-   #   id: pytester
-   #   continue-on-error: false   # we want this to fail if unit tests are broken, job2 will let us know it failed,
-   #   run: .github/workflows/biopypir_helper.sh "TEST";     #  unless job2 needs: [job1]
+    - name: simple pytest
+      id: pytester
+      run: .github/workflows/biopypir_helper.sh "TEST";     #  unless job2 needs: [job1]
    #===============================================#
     #- name: check pytest pass
     #  id: pytestpass
     #  if: success()
     #  run: echo "::set-output name=pytestpass::True" 
     #===============================================#
-   # - name: PIP deployment test    # make sure this fails if deployment fails, does OS matter here?
-   #   continue-on-error: true
-   #   uses: BSFishy/pip-action@v1
-   #   with:
-   #     packages: scedar   #==0.2.0  # use ${{github.repository}} to hardcode
-   #===============================================#
-   # - name: PIP pass check
-   #   id: pipcheck
-   #   if: success()
-   #   run: echo "::set-output name=pip_output::True"  
-    #===============================================#
-    - name: check license
-      if: startsWith(matrix.os, 'ubuntu')
-      uses: datreeio/validate-license-action@master
+    - name: PIP deployment test    # make sure this fails if deployment fails, does OS matter here?
+      continue-on-error: true
+      uses: BSFishy/pip-action@v1
       with:
-        args: "MIT, ISC"  #"Apache License 2.0, MIT, ISC"
+        packages: scedar   #==0.2.0  # use ${{github.repository}} to hardcode
+   #===============================================#
+    - name: PIP pass check
+      id: pipcheck
+      if: success()
+      run: echo "::set-output name=pip_output::True"  
     #===============================================#
-    - name: license pass check   # alter the actual license-check action (bash fnc from js env) 
-      id: licensecheck           # to output PASS on success
-      if: success()     
-      run: echo "::set-output name=license_output::True"
+    #- name: check license
+    #  if: startsWith(matrix.os, 'ubuntu')
+    #  uses: datreeio/validate-license-action@master
+    #  with:
+    #    args: "MIT,ISC,BSD"  #"Apache License 2.0, MIT, ISC"
     #===============================================#
-    - name: print lint var
+    #- name: license pass check   # alter the actual license-check action (bash fnc from js env) 
+    #  id: licensecheck           # to output PASS on success
+    #  if: success()     
+    #  run: echo "::set-output name=license_output::True"
+   #===============================================#
+    - name: gather outputs
+      id: file
       run: |
           .github/workflows/biopypir_helper.sh  "GATHER" \
           "${{github.repository}}" \
           "${{steps.linter.outputs.pylint-score}}" \
-          "${{steps.licensecheck.outputs.license_output}}" \
           "${{matrix.python-version}}" \
-          "${{matrix.os}}"
+          "${{matrix.os}}" \
+          "${{github.run_id}}"
      #   "${{steps.builder.outputs.build_output}}" \
      #   "${{steps.pytester.outputs.pytest_score}}" \
      #   "${{steps.pipcheck.outputs.pip_output}}" \
      #   "${{steps.pytestpass.outputs.pytestpass}}" \
      #   "${{matrix.python-version}}" 
    #===============================================#
-   # - run: cat full_report.json
-    
     - name: Upload artifact
-      uses: actions/upload-artifact@v1.0.0
-      with:
-        name: ${{matrix.os}}-py${{matrix.python-version}}
-        path: ${{matrix.os}}-py${{matrix.python-version}}.json
-            
+      uses: actions/upload-artifact@v2-preview
+      with:  
+        name: biopypir-${{matrix.os}}-py${{matrix.python-version}}
+        path: "*-latest-*.json"   #${{matrix.os}}-py${{matrix.python-version}}.json
+    
   job2:
-      needs: [biopypir_testing]
+      needs: [biopypir_testing] #runs if at least one job succeeds?
       if: always()
       runs-on: [ubuntu-latest]
       steps:
+        - name: STEP 1. Check-Out Repo 
+          uses: actions/checkout@v2 
+        #===============================================# 
         - name: Download artifact
           uses: actions/download-artifact@v2-preview
-
-        - name: check the jobs
-          id: mystatus
-          run: |
-            (curl -X GET -s -u "admin:${{ secrets.PAT3 }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
-            | jq ".jobs[] | {job_status: .conclusion, matrix: .name}") > mystatus.json
-            cat mystatus.json
-
-        - name: Upload artifact
-          uses: actions/upload-artifact@v1.0.0
           with:
-            name:  mystatus
-            path:  mystatus.json
-
+            path: parallel_runs/
+        - name: list artifacts
+          run: |
+              pwd; ls; cd parallel_runs; ls
+        #===============================================#
+        - name: check the jobs
+          run:  |
+              chmod +x .github/workflows/biopypir_helper.sh
+              .github/workflows/biopypir_helper.sh  "EVAL" ${{github.repository}} ${{github.run_id}}
+        #===============================================#
+        - name: Global webhook
+          if: always() 
+          uses: muinmomin/webhook-action@v1.0.0
+          with:
+            url: ${{ secrets.WEBHOOK_URL }}
+            data: "{mystatus.json}"
